### ISSUE TITLE
Request for OpenGL 2.1 support

### ISSUE THREAD

**Issue by taingra** [vydd/sketch#10]
Very interesting project, sadly I cannot make use of it because my hardware only supports OpenGL 2.1 not 3.3, and it's not something that my current situation really allows me to change anytime soon. 

I don't really know how hard of an issue this would be to solve. I understand if it is unfeasible, I just figured I'd at least let you know that there are people that would appreciate wider OpenGL support.

**Comment by vydd** [comment]
Unfortunately, I don't think I'd be able to support both versions. Right now, I'm probably not using too many 3.3 specific features, so you're absolutely welcome to fork Sketch and try making an OpenGL 2.1 version. That might also help in future with embedded devices, for example.

If you decide to do that, I'll help you get started, and if you complete the conversion I'll link to it from the README, but I can't offer much more. Also I'd like to avoid having to deal with backwards compatibility with this codebase as long as possible, so I'm not sure if I'd be ready to merge back the changes.

Thanks for stopping by!
