### ISSUE TITLE
More informative errors

### ISSUE THREAD

**Issue by honix** [vydd/sketch#13]
If any error executed (in game-logic for example), sketch becomes red and speechless about whats wrong. Maybe there is some way to debug these errors, but i'm can't get it.

It will be very handy to see what kind of error i have.

**Comment by vydd** [comment]
So there's no error text, just the red screen? Can you print text at all using `#'TEXT`, for example, `(text "hello" 100 100)`? You should be getting something similar to http://imgur.com/PQRTy9G , not just the red screen. What OS and CL implementation are you using?

**Comment by honix** [comment]
There is mine http://imgur.com/a/ocVDc
Sketch version from quicklisp repo
I'm on Fedora 23 and SBCL 1.3.4

**Comment by honix** [comment]
Oh, my fault. Got same message as you shown after updated to github version. Sorry for annoying.

**Comment by vydd** [comment]
By the way, the quicklisp dist just got updated, so if you run `(ql:update-dist "quicklisp")`, and quickload sketch again, you can get the current version from there as well ;)
