### ISSUE TITLE
Tons of lines and garbage collector

### ISSUE THREAD

**Issue by honix** [vydd/sketch#14]
When there is many dynamic lines:
https://gist.github.com/honix/e94f42eb24e62a2ade8cbb45ab8b9df1

Sketch becomes little laggy because of GC hard work. So, for now i down `*shape-cache-capacity*` to zero and have smooth animation. I think it needs to rethink caches somehow..

**Comment by vydd** [comment]
Thanks for reporting this, you are right. I'm working on a much better solution (keeping everything in gfx memory with better defaults). I'm hoping to have it completed before the next QL release.

**Comment by vydd** [comment]
Fixed in April release (removed caching). Will try doing this again - but in a smarter way - once CEPL backend is ready.
