### ISSUE TITLE
No input on OS X

### ISSUE THREAD

**Issue by crumbtoo** [vydd/sketch#164]
I can't seem to get input working despite the window opening fine. Oddly enough, input works in the examples (life) but not when the exact code for the examples is cut-and-pasted. Both are loaded via `make-instance` in the REPL.

```
System Version: macOS 12.6 (21G115)
```
```
$ ccl64 --version
Clozure Common Lisp Version 1.12.2  DarwinX8664
```

Update: It looks like the version on quicklisp is outdated compared to the readme and expected an older API.

**Comment by Kevinpgalligan** [comment]
Yeah, there hasn't been a quicklisp release in a long time!

**Comment by crumbtoo** [comment]
I should’ve caught that :p. New to CL and its ecosystem.
