### ISSUE TITLE
Changed colors with load image

### ISSUE THREAD

**Issue by ulrivo** [vydd/sketch#32]
If I load a PNG-file, instead of red the color blue is rendered.

`(defsketch image
  ((title "image") (width 500) (height 600))
  (image (load-resource "png/my-image.png") 100 50)
`

**Comment by vydd** [comment]
Hey @ulrivo,

Is this the same for every image?
Which platform are you on? (lisp, os)
If not all images are shown like this, could you send me the exact image you're using?

Thanks!

**Comment by ulrivo** [comment]
I tried different PNG-files, the colors are always twisted - wrong texture?

I am using CCL64 (Clozure Common Lisp Version 1.11.6  DarwinX8664) on Mac OS X and attach a PNG which is shown in blue instead of red.

![10_of_hearts](https://user-images.githubusercontent.com/1521098/66770895-0a427a00-eeb9-11e9-8ed5-dabe6f1bd958.png)

**Comment by n00p3** [comment]
I have the same issue, changing `:bgra` to `:rgba` [here](https://github.com/vydd/sketch/blob/1a2e4bba865d5083889c68f8755ef6c0e2a7d5a2/src/resources.lisp#L88) solves this problem.
SBCL 2.1.5
Manjaro x64

**Comment by vydd** [comment]
@n00p3 any ideas on how we could identify the correct parameter here?

**Comment by n00p3** [comment]
@vydd 
Quick & dirty solution would be to use imagemagick to identify colorspace of image
`identify -verbose image.png | grep Colorspace | awk '{ print $2 }'` but this is far from acceptable answer. I don't know much of OpenGL to help with this topic.
How about letting user specify format when loading resource? Something like this `(load-resource "image.png" :format :rgba)`
