### ISSUE TITLE
[feature?] is it possible to prevent clear screen at each redraw

### ISSUE THREAD

**Issue by Inc0n** [vydd/sketch#37]
I currently in the process of learning a bit about processing.
I started with `:trivial-gamekit`. However, I disliked the idea of refreshing the screen at every draw.
Especially for simple programs like random walker, wouldn't be much better if the program continuously draw, instead of keeping a list of objects drawn.

So is there a way to achieve this?

**Comment by Average-user** [comment]
@Inc0ns1st3nt did you managed to do it? At least in [quil](http://www.quil.info/), the processing library for Clojure it is possible.

**Comment by vydd** [comment]
@Inc0n Have you tried setting `COPY-PIXELS` to `T` like in https://github.com/vydd/sketch/blob/master/examples/brownian.lisp#L15 ?

**Comment by Inc0n** [comment]
Unfortunately it has been so long that I could not find the original source files, but it would seem that this would fix my issue.
Thanks
