### ISSUE TITLE
Is there a way to render an array of pixels?

### ISSUE THREAD

**Issue by TatriX** [vydd/sketch#44]
Hi!
I'm trying to render a 2d array of pixels and it seems there is no simple way of doing this.
I'm looking for something similar to [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas) or [p5](https://p5js.org/reference/#/p5/loadPixels) / [processing](https://processing.org/reference/pixels.html)

**Comment by vydd** [comment]
Hey, not at the moment! Would you expect that to work as a texture?

**Comment by TatriX** [comment]
I guess. I was trying to manually generate Perlin noise iirc. It's been a while :)

**Comment by vydd** [comment]
Hey! I've added the canvas here 1be59d2c44b5cd8c54e34b4931133f1020474e2b.
It needs some polish and docs, but I'm pretty happy with how it works in general.

Here's what I made with it (the new example):

![stars-demo](https://user-images.githubusercontent.com/2054352/200203225-a5eaa6c8-fd63-46ee-9b7f-41014a3675a3.gif)
