### ISSUE TITLE
The appropriate way to set a custom font

### ISSUE THREAD

**Issue by VitoVan** [vydd/sketch#48]
Currently, I use the following code to achieve the custom font:

```lisp
(set-font
 (make-font
  :face (make-instance 'sketch::typeface :filename "/tmp/my-stupid-font.ttf")))
```

I basically know nothing about SDL, and know very little about Common Lisp.

And the code above used something like `sketch::typeface`, which makes me feel inelegant. Since the double colons (`::`) tell me that you do not want me to use it.

So I am wondering:

Is this the proper way to set a custom font?

If not, what should I do?

Thank you very much for creating `sketch`, I enjoyed it very much.

**Comment by dawranliou** [comment]
Hi @VitoVan, I happened to be looking at the [QELT](https://github.com/vydd/qelt/blob/master/qelt.lisp) repo and found [`sketch:load-resource`](https://github.com/vydd/sketch/blob/4cc00b08e202c7adda41391463096cf9df1705c3/src/resources.lisp#L52) the function you are looking for.  This function checks the resource's file extension and creates the typeface instance so you can do:

```
(set-font
 (make-font
  :face (sketch:load-resource"/tmp/my-stupid-font.ttf")))
```
