### ISSUE TITLE
How to run sketch across VNC?

### ISSUE THREAD

**Issue by mirkov** [vydd/sketch#49]
Hello,

I am accessing sketch from a Windows laptop via VNC to a CentOS server (no graphics card on server).

I cannot run Sketch examples from Emacs/slime, so I am trying to debug the issue by first running the examples in sbcl running from a Gnome terminal.

I was able to run CL-SDL2 example in that sbcl.

Back to Sketch. After setting the `SDL_VIDEO_X11-VISUALID` to `0x210`, I get a black window with error `SDL error: could not generate GLX context`.

Two questions:

- Does anyone know how to deal with the GLX context error (I could not follow the discussions and solutions that I found on the web)
- Does anyone have sketch running across VNC and can share their setup?

I realize that these issues are Lisp and Sketch unrelated, but I am hoping someone has them figured out. I also understand that this topic is quite complex, and this forum may not be the right place to look for answers.

Thanks,

Mirko

**Comment by aykaramba** [comment]
You need a graphics card to process the glx calls to get that to work.

**Comment by mirkov** [comment]
Well, my servers don't have graphics cards, so you are onto something :-)

I'll dig a bit more into SDL on non-Graphics Card machines.
