### ISSUE TITLE
Attempting to render images results in a garbled mess.

### ISSUE THREAD

**Issue by SkiHatDuckie** [vydd/sketch#63]
When trying to load and render any PNG image, the image comes out as a garbled mess. I have, quite literally, 1 week of experience with common lisp, so my understanding of why this is happening is a bit limited.

Minimal-ish example:
```
(asdf:load-system :cffi)

(cffi:define-foreign-library libffi  ; Required for loading sketch.
  (t (:default "libffi-7")))

(cffi:use-foreign-library libffi)

(ql:quickload :sketch)

(defpackage :stickies (:use :cl :sketch))
(in-package :stickies)

...

(defsketch app 
    ((title "Stickies") (width 600) (height 400)
    (save-icon (load-resource "..\\assets\\StickiesSaveIcon.png")))
  (image save-icon 0 0))

(defun main ()
  (make-instance 'app))

(main)
```
The image I'm trying to draw to the screen:
![saveIconTemp](https://user-images.githubusercontent.com/63932363/204439334-a0be7975-7914-4583-997b-75c6d4a6b211.png)
What I'm getting:
![saveIconRenderResult](https://user-images.githubusercontent.com/63932363/204439693-2c624bd3-387e-4635-b54a-b1ca364f07e6.png)
My operating system is Windows 10, and I've been using SBCL 2.2.10.

**Comment by Kevinpgalligan** [comment]
It draws fine for me, but the colour comes out as red instead of purple.

![icon](https://user-images.githubusercontent.com/8592196/209692395-ac119c17-03c0-46da-9585-bf99229a9b23.png)

I execute all the code in the REPL, and load `sketch` with quicklisp.

```
(ql:quickload 'sketch)
To load "sketch":
  Load 1 ASDF system:
    sketch
; Loading "sketch"
.........
(SKETCH)
CL-USER> (in-package sketch)
#<PACKAGE "SKETCH">
SKETCH> (defsketch app
            ((title "Stickies")
             (width 600)
             (height 400)
             (save-icon (load-resource "/home/kg/Descargas/icon.png")))
          (image save-icon 0 0))
#<STANDARD-CLASS SKETCH::APP>
SKETCH> (make-instance 'app)
#<APP {100492DEE3}>
SKETCH> 
```

**Comment by SkiHatDuckie** [comment]
I just tried running your code in the REPL myself, but got the same mess as before.

I'm starting to wonder if this has something to do with the external dependencies.
I tried running the following in the REPL:
```
* (ql:quickload :sdl2-ttf-examples) 
To load "sdl2-ttf-examples":
  Load 1 ASDF system:
    sdl2-ttf-examples
; Loading "sdl2-ttf-examples"
..
(:SDL2-TTF-EXAMPLES)
* (ttf-examples:gl-example)
```
And I got this:
![openGLContext](https://user-images.githubusercontent.com/63932363/210151839-4cf2cf58-425f-4197-9ccc-7859cb922f49.png)
But when I tried `(ttf-examples:basic-example)`, it renders perfectly fine!
![BasicFontExample](https://user-images.githubusercontent.com/63932363/210151880-33a0ebd8-6a68-4702-9c54-f0206d191f20.png)
So now I'm wondering if this has something to do with OpenGL (using NVIDIA version 4.6) (???)

**Comment by Gleefre** [comment]
Hello! These results seems to be similar to https://github.com/vydd/sketch/issues/32 and https://github.com/vydd/sketch/issues/51. Did you used latest version of sketch (cloning this repo)?

**Comment by SkiHatDuckie** [comment]
Everything works now! Thank you.
![goddammit2](https://user-images.githubusercontent.com/63932363/210159180-753cdde7-12e4-4ff8-9f44-afef099851cb.png)
Now I just feel stupid, because I actually remember stumbling upon #55 earlier on into figuring this out, but I guess I looked at the date it was merged and then just assumed that it was already a part of the quicklisp release.

**Comment by Kevinpgalligan** [comment]
Ah, I also remember that issue, but I didn't realise it had been fixed.
