### ISSUE TITLE
Further improvements / maintenance

### ISSUE THREAD

**Issue by Gleefre** [vydd/sketch#80]
Hello,

Due to the library becoming stale, as @Kevinpgalligan suggested in #74, I'll keep working on it at my fork only: https://github.com/Gleefre/sketch. Feel free to open pull requests and raise new issues there :).

@vydd if you choose to resume your work on sketch, I would be glad to open several pull-requests to backport our changes.

**Comment by vydd** [comment]
Hey @Gleefre ! Sorry for not doing a good job at reviewing, super busy times.

You are of course free to maintain a fork, but I feel it'd be better for everyone if we found a way to get your changes into here.

If you would describe where you want to go with the fork/changes, it'd be much easier for me to review at a more regular cadence. As it stands, whenever I do it, it's a huge context switch for me, as figuring out why someone is proposing a certain change at a certain time can be difficult.

**Comment by Gleefre** [comment]
Hi!

Not sure what you mean by where I want to go; but my goal is to create a faster moving branch, that would be easier to contribute to (for me as well as for others).

Aside from small bug fixes I also plan to work on features like
- easier building for applications. `define-start-function` is currently working, but I'm still thinking about its API.
- fix the default width/height solution I've been using - which would probably include rewriting `defsketch` macro and removing the `prepare` method.
- separate the public API from the SDL2/OpenGL backend. Maybe add other backends.
- exposing some internals of the backend, for example to get a configurable mag filter in openGL to resize images without them getting blurred.
- figure out for myself and maybe document sketch components like shaders, figures, controllers and channels.

**Comment by vydd** [comment]
I can go through PRs later today if you reopen them. Let's try to make this work.

**Comment by Gleefre** [comment]
Alright :).

**Comment by Gleefre** [comment]
I'll be closing this issue now.

Do you plan to actively work on sketch, or you are just reviewing PR for now?

**Comment by vydd** [comment]
Let's say it's reviewing PRs for now and discussion. I am actively thinking about channels again, though.

---- 

Here's something else you can do with channels (as a continuation from our irc discussion... maybe we should create an issue for it):

```lisp
(defsketch add 
    ((c (in :c 0)))
  (text (format nil "~a" c) 100 100))

(define-channel-observer
  (out :c (+ (in :a 0) (in :b 0))))
```

with that defined, you can see the number changing as you send numbers to :a and :b in repl (using `(out :a 5)`)
